#!/usr/bin/env perl
use strict;
use warnings;
use lib 'lib';
use lib '../lib';
use Lock::Socket qw/lock_socket/;

die "usage: $0 PORT COMMAND...\n"
  unless $#ARGV >= 1;

# Unset close-on-exec
$^F = 3;

my $lock = lock_socket( shift @ARGV );
print "Have lock on " . $lock->addr . ':' . $lock->port . "\n";

exec @ARGV
  or die "exec: $!";
