---
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.12'
license: gpl3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lock-Socket
no_index:
  directory:
    - example
    - inc
    - t
  package:
    - Lock::Socket::Error
    - Lock::Socket::Mo
requires:
  Carp: 0
  Socket: 0
  perl: 5.6.0
resources:
  bugtracker: https://github.com/mlawren/p5-Lock-Socket/issues
  homepage: https://github.com/mlawren/p5-Lock-Socket
  license: http://opensource.org/licenses/gpl-3.0.html
  repository: git://github.com/mlawren/p5-Lock-Socket.git
version: 0.0.5_1
